### ISSUE TITLE
scraping color values from a screen

### ISSUE THREAD

**Issue by chiapet92** [RazorTag/runescape_bot#2]
Look into how to implement a system to retrieve color values from a program window in C#. This will allow us to use color recognition to use in the lesser demon bot and (other bots to come).

**Comment by chiapet92** [comment]
http://stackoverflow.com/questions/254197/how-can-i-get-the-active-screen-dimensions
^ this will retrieve the screen dimensions of the active screen. Can work as a step one to retrieve the boundaries that we'll need to retrieve pixels from.

**Comment by RazorTag** [comment]
It reads from the client, but the client has to be visible. Reading from the client when it is hidden produces what appears to be the default minimize/resize/close icons for a window. I don't think that OSBuddy is even rendering when it isn't visible.

Right now, the output from the screen reader is an IntPtr to a bitmap. I am trying to figure out how to use a proper Bitmap object reference so that we have type checking.
